// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import { Test } from "forge-std/Test.sol";

import { IStrategyTypes } from "../../contracts/core/interfaces/IStrategyTypes.sol";
import { RuleEngineLib } from "../../contracts/libraries/RuleEngineLib.sol";

/// @title ReferenceEngineDifferentialTest
/// @notice Replays a fixture generated by an independent Python implementation
///         (`sim/reference_engine.py`) through the real `RuleEngineLib.evaluate` and asserts every
///         field of every resulting state matches.
///
/// @dev Both implementations decode the exact same compiled bytecode
///      (`test/compiler/golden/volatility-shield.bytecode.hex`) rather than a hand-described
///      version of the strategy's logic, so this catches divergence in either the bytecode decoder
///      or the evaluation semantics — not just "the Python author agreed with the Solidity author
///      about what the strategy should do."
///
///      Regenerate the fixture after a deliberate change to RuleEngineLib or RuleProgram with:
///        python sim/generate_vectors.py
///      and review the diff before trusting it — an unreviewed regeneration would let a bug in
///      the Python model "confirm" a matching bug in Solidity.
contract ReferenceEngineDifferentialTest is Test {
    bytes internal program;

    /// @dev Matches the exact step count `sim/generate_vectors.py` writes (10 scripted + 90 random).
    uint256 internal constant STEP_COUNT = 100;

    function setUp() public {
        string memory hexPath = "test/compiler/golden/volatility-shield.bytecode.hex";
        string memory hexStr = vm.readLine(hexPath);
        program = vm.parseBytes(hexStr);
    }

    function test_MatchesPythonReferenceEngineAcrossAllVectors() public view {
        string memory json = vm.readFile("test/differential/vectors.json");

        for (uint256 i = 0; i < STEP_COUNT; i++) {
            string memory p = string.concat(".steps[", vm.toString(i), "]");

            IStrategyTypes.RuntimeState memory before = IStrategyTypes.RuntimeState({
                mode: IStrategyTypes.StrategyMode(vm.parseJsonUint(json, string.concat(p, ".beforeMode"))),
                referencePrice: vm.parseJsonUint(json, string.concat(p, ".beforeReferencePrice")),
                liquidityBps: uint16(vm.parseJsonUint(json, string.concat(p, ".beforeLiquidityBps"))),
                spreadBps: uint16(vm.parseJsonUint(json, string.concat(p, ".beforeSpreadBps"))),
                lastTransition: uint64(vm.parseJsonUint(json, string.concat(p, ".beforeLastTransition"))),
                lastExecution: uint64(vm.parseJsonUint(json, string.concat(p, ".beforeLastExecution"))),
                cumulativeVolume: vm.parseJsonUint(json, string.concat(p, ".beforeCumulativeVolume")),
                transitionCount: uint64(vm.parseJsonUint(json, string.concat(p, ".beforeTransitionCount"))),
                armedRule: uint8(vm.parseJsonUint(json, string.concat(p, ".beforeArmedRule"))),
                armedSince: uint64(vm.parseJsonUint(json, string.concat(p, ".beforeArmedSince")))
            });

            IStrategyTypes.MarketState memory market = IStrategyTypes.MarketState({
                price: vm.parseJsonUint(json, string.concat(p, ".marketPrice")),
                volatility: vm.parseJsonUint(json, string.concat(p, ".marketVolatility")),
                priceChange5m: int256(vm.parseJsonUint(json, string.concat(p, ".marketPriceChange5m"))),
                priceChange1h: int256(vm.parseJsonUint(json, string.concat(p, ".marketPriceChange1h"))),
                volume: vm.parseJsonUint(json, string.concat(p, ".marketVolume")),
                oracleConfidence: vm.parseJsonUint(json, string.concat(p, ".marketOracleConfidence")),
                timestamp: vm.parseJsonUint(json, string.concat(p, ".marketTimestamp"))
            });

            uint256 nowTs = vm.parseJsonUint(json, string.concat(p, ".now"));

            (IStrategyTypes.RuntimeState memory got,) = RuleEngineLib.evaluate(before, market, program, nowTs);

            string memory ctx = string.concat("step ", vm.toString(i));
            assertEq(uint8(got.mode), vm.parseJsonUint(json, string.concat(p, ".afterMode")), string.concat(ctx, ": mode"));
            assertEq(
                got.referencePrice, vm.parseJsonUint(json, string.concat(p, ".afterReferencePrice")), string.concat(ctx, ": referencePrice")
            );
            assertEq(got.liquidityBps, vm.parseJsonUint(json, string.concat(p, ".afterLiquidityBps")), string.concat(ctx, ": liquidityBps"));
            assertEq(got.spreadBps, vm.parseJsonUint(json, string.concat(p, ".afterSpreadBps")), string.concat(ctx, ": spreadBps"));
            assertEq(
                got.lastTransition, vm.parseJsonUint(json, string.concat(p, ".afterLastTransition")), string.concat(ctx, ": lastTransition")
            );
            assertEq(
                got.cumulativeVolume,
                vm.parseJsonUint(json, string.concat(p, ".afterCumulativeVolume")),
                string.concat(ctx, ": cumulativeVolume")
            );
            assertEq(
                got.transitionCount,
                vm.parseJsonUint(json, string.concat(p, ".afterTransitionCount")),
                string.concat(ctx, ": transitionCount")
            );
            assertEq(got.armedRule, vm.parseJsonUint(json, string.concat(p, ".afterArmedRule")), string.concat(ctx, ": armedRule"));
            assertEq(got.armedSince, vm.parseJsonUint(json, string.concat(p, ".afterArmedSince")), string.concat(ctx, ": armedSince"));
        }
    }
}
