// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import { Test } from "forge-std/Test.sol";

import { IPoolManager } from "@uniswap/v4-core/src/interfaces/IPoolManager.sol";
import { PoolKey } from "@uniswap/v4-core/src/types/PoolKey.sol";
import { Currency } from "@uniswap/v4-core/src/types/Currency.sol";
import { IHooks } from "@uniswap/v4-core/src/interfaces/IHooks.sol";
import { Hooks } from "@uniswap/v4-core/src/libraries/Hooks.sol";
import { LPFeeLibrary } from "@uniswap/v4-core/src/libraries/LPFeeLibrary.sol";
import { HookMiner } from "@uniswap/v4-periphery/src/utils/HookMiner.sol";

import { ISwapVM } from "@1inch/swap-vm/src/interfaces/ISwapVM.sol";
import { MakerTraitsLib } from "@1inch/swap-vm/src/libs/MakerTraits.sol";

import { ConditionalLiquidityRegistry } from "../../contracts/core/ConditionalLiquidityRegistry.sol";
import { StrategyValidator } from "../../contracts/core/StrategyValidator.sol";
import { ConditionalLiquidityEngine } from "../../contracts/engine/ConditionalLiquidityEngine.sol";
import { ConditionalLiquidityHook } from "../../contracts/uniswap/ConditionalLiquidityHook.sol";
import { MockERC20 } from "../../contracts/mocks/MockERC20.sol";
import { MockMarketStateProvider } from "../../contracts/mocks/MockMarketStateProvider.sol";
import { IStrategyTypes } from "../../contracts/core/interfaces/IStrategyTypes.sol";
import { StrategyLib } from "../../contracts/libraries/StrategyLib.sol";
import { StrategyFixtures } from "../utils/StrategyFixtures.sol";

/// @title UniswapBackendDifferentialTest
/// @notice Replays the SAME 100-step fixture `test/differential/vectors.json` (generated by the
///         independent Python reference engine, `sim/reference_engine.py`, and already checked
///         against `RuleEngineLib.evaluate` directly in `ReferenceEngine.t.sol`) against a strategy
///         registered through the Uniswap v4 hook's own registry/engine deployment.
///
/// @dev This closes the transitive chain: Python == Solidity RuleEngineLib (ReferenceEngine.t.sol)
///      and SwapVM backend == Uniswap backend on the same sequence (StrategyEquivalence.t.sol)
///      together already imply Python == Uniswap backend, but this test checks it directly and at
///      the full 100-scenario scale, through the actual registry a pool-bound strategy uses
///      (`ConditionalLiquidityHook`'s `REGISTRY`/`ENGINE`), not just the bare library.
contract UniswapBackendDifferentialTest is Test {
    ConditionalLiquidityRegistry internal registry;
    ConditionalLiquidityEngine internal engine;
    MockMarketStateProvider internal oracle;
    ConditionalLiquidityHook internal hook;
    bytes32 internal strategyId;

    address internal maker = makeAddr("diffMaker");
    address internal owner = makeAddr("diffOwner");

    uint256 internal constant STEP_COUNT = 100;

    function setUp() public {
        MockERC20 a = new MockERC20("Diff Token X", "DFX", 18);
        MockERC20 b = new MockERC20("Diff Token Y", "DFY", 18);
        (address lo, address hi) = StrategyLib.sortTokens(address(a), address(b));

        registry = new ConditionalLiquidityRegistry(new StrategyValidator(), owner);
        oracle = new MockMarketStateProvider();
        engine = new ConditionalLiquidityEngine(registry, oracle);
        vm.prank(owner);
        registry.setStateAuthority(address(engine));

        IPoolManager manager = IPoolManager(vm.deployCode("PoolManager.sol:PoolManager", abi.encode(owner)));
        uint160 flags = uint160(Hooks.BEFORE_SWAP_FLAG);
        bytes memory constructorArgs = abi.encode(manager, engine, registry);
        (address predicted, bytes32 salt) =
            HookMiner.find(address(this), flags, type(ConditionalLiquidityHook).creationCode, constructorArgs);
        hook = new ConditionalLiquidityHook{ salt: salt }(manager, engine, registry);
        require(address(hook) == predicted, "hook address mismatch");

        PoolKey memory poolKey = PoolKey({
            currency0: Currency.wrap(lo),
            currency1: Currency.wrap(hi),
            fee: LPFeeLibrary.DYNAMIC_FEE_FLAG,
            tickSpacing: 60,
            hooks: IHooks(address(hook))
        });
        manager.initialize(poolKey, uint160(1) << 96);

        MakerTraitsLib.Args memory args;
        args.maker = maker;
        args.tokenA = lo;
        args.tokenB = hi;
        args.useAquaInsteadOfSignature = true;
        args.program = hex"5000";
        ISwapVM.Order memory order = MakerTraitsLib.build(args);

        vm.prank(maker);
        strategyId = registry.registerStrategy(
            order, StrategyFixtures.NORMAL_LIQ, StrategyFixtures.NORMAL_SPREAD, StrategyFixtures.volatilityShield()
        );
        vm.prank(maker);
        hook.registerPoolStrategy(poolKey, strategyId, 100 ether, 100 ether);
    }

    function test_UniswapRegisteredStrategyMatchesPythonReferenceAcrossAllVectors() public {
        string memory json = vm.readFile("test/differential/vectors.json");

        for (uint256 i = 0; i < STEP_COUNT; i++) {
            string memory p = string.concat(".steps[", vm.toString(i), "]");

            uint256 nowTs = vm.parseJsonUint(json, string.concat(p, ".now"));
            vm.warp(nowTs);

            oracle.setVolatility(
                strategyId,
                vm.parseJsonUint(json, string.concat(p, ".marketVolatility")),
                vm.parseJsonUint(json, string.concat(p, ".marketPrice"))
            );

            engine.poke(strategyId);
            IStrategyTypes.RuntimeState memory got = registry.getStrategyState(strategyId);

            string memory ctx = string.concat("step ", vm.toString(i));
            assertEq(uint8(got.mode), vm.parseJsonUint(json, string.concat(p, ".afterMode")), string.concat(ctx, ": mode"));
            assertEq(got.liquidityBps, vm.parseJsonUint(json, string.concat(p, ".afterLiquidityBps")), string.concat(ctx, ": liquidityBps"));
            assertEq(got.spreadBps, vm.parseJsonUint(json, string.concat(p, ".afterSpreadBps")), string.concat(ctx, ": spreadBps"));
            assertEq(
                got.transitionCount,
                vm.parseJsonUint(json, string.concat(p, ".afterTransitionCount")),
                string.concat(ctx, ": transitionCount")
            );
        }
    }
}
