// Generated by scripts/sync-abis.mjs from out/AquaVenue.sol/AquaVenue.json — do not edit.
// Re-run `npm run sync-abis` after any `forge build`.

export const aquaVenueAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "aqua",
        "type": "address",
        "internalType": "contract IAqua"
      },
      {
        "name": "router",
        "type": "address",
        "internalType": "contract AquaSwapVMRouter"
      },
      {
        "name": "engine",
        "type": "address",
        "internalType": "contract IConditionalLiquidityEngine"
      },
      {
        "name": "registry",
        "type": "address",
        "internalType": "contract IConditionalLiquidityRegistry"
      },
      {
        "name": "strategyId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "order",
        "type": "tuple",
        "internalType": "struct ISwapVM.Order",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "traits",
            "type": "uint256",
            "internalType": "MakerTraits"
          },
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "AQUA",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAqua"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ENGINE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IConditionalLiquidityEngine"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "REGISTRY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IConditionalLiquidityRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ROUTER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract AquaSwapVMRouter"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "STRATEGY_ID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "executableLiquidity",
    "inputs": [
      {
        "name": "tokenIn",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IExecutableLiquidity.ExecutableLiquidity",
        "components": [
          {
            "name": "virtualLiquidity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "walletLiquidity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "allowance",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deliverableLiquidity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "conditionalLiquidity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "coverageBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "execute",
    "inputs": [
      {
        "name": "tokenIn",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minAmountOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "snapshot",
    "inputs": [
      {
        "name": "tokenIn",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct ILiquidityVenue.VenueSnapshot",
        "components": [
          {
            "name": "venue",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "strategyId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "mode",
            "type": "uint8",
            "internalType": "enum IStrategyTypes.StrategyMode"
          },
          {
            "name": "effectiveLiquidity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "spreadBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "referencePrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "coverageBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "SafeCastOverflowedUintDowncast",
    "inputs": [
      {
        "name": "bits",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TakerTraitsMissingHasPreTransferInFlag",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TakerTraitsMissingHasPreTransferOutFlag",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TakerTraitsThresholdLengthInvalid",
    "inputs": [
      {
        "name": "threshold",
        "type": "bytes",
        "internalType": "bytes"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownPair",
    "inputs": [
      {
        "name": "tokenIn",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "internalType": "address"
      }
    ]
  }
] as const;
