// Generated by scripts/sync-abis.mjs from out/ConditionalLiquidityEngine.sol/ConditionalLiquidityEngine.json - do not edit.
// Re-run `npm run sync-abis` after any `forge build`.

export const conditionalLiquidityEngineAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "registry",
        "type": "address",
        "internalType": "contract IConditionalLiquidityRegistry"
      },
      {
        "name": "oracle",
        "type": "address",
        "internalType": "contract IMarketStateProvider"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ORACLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IMarketStateProvider"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "REGISTRY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IConditionalLiquidityRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "effectiveLiquidity",
    "inputs": [
      {
        "name": "strategyId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "makerBalance",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "poke",
    "inputs": [
      {
        "name": "strategyId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "config",
        "type": "tuple",
        "internalType": "struct IStrategyTypes.LiquidityConfig",
        "components": [
          {
            "name": "liquidityBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "spreadBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "mode",
            "type": "uint8",
            "internalType": "enum IStrategyTypes.StrategyMode"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "preview",
    "inputs": [
      {
        "name": "strategyId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "next",
        "type": "tuple",
        "internalType": "struct IStrategyTypes.RuntimeState",
        "components": [
          {
            "name": "mode",
            "type": "uint8",
            "internalType": "enum IStrategyTypes.StrategyMode"
          },
          {
            "name": "referencePrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "liquidityBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "spreadBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "lastTransition",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastExecution",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "cumulativeVolume",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "transitionCount",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "armedRule",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "armedSince",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "config",
        "type": "tuple",
        "internalType": "struct IStrategyTypes.LiquidityConfig",
        "components": [
          {
            "name": "liquidityBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "spreadBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "mode",
            "type": "uint8",
            "internalType": "enum IStrategyTypes.StrategyMode"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "LiquidityConfigurationChanged",
    "inputs": [
      {
        "name": "strategyId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "liquidityBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "spreadBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StateTransition",
    "inputs": [
      {
        "name": "strategyId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "previousMode",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum IStrategyTypes.StrategyMode"
      },
      {
        "name": "newMode",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum IStrategyTypes.StrategyMode"
      },
      {
        "name": "timestamp",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "triggerVolatilityBps",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "ProgramTruncated",
    "inputs": [
      {
        "name": "needed",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "available",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "StrategyNotActive",
    "inputs": [
      {
        "name": "strategyId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownActionType",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownComparison",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownConditionType",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;
