// Generated by scripts/sync-abis.mjs from out/MockMarketStateProvider.sol/MockMarketStateProvider.json - do not edit.
// Re-run `npm run sync-abis` after any `forge build`.

export const mockMarketStateProviderAbi = [
  {
    "type": "function",
    "name": "getMarketState",
    "inputs": [
      {
        "name": "strategyId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IStrategyTypes.MarketState",
        "components": [
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "volatility",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "priceChange5m",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "priceChange1h",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "volume",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "oracleConfidence",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setDefaultMarketState",
    "inputs": [
      {
        "name": "state",
        "type": "tuple",
        "internalType": "struct IStrategyTypes.MarketState",
        "components": [
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "volatility",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "priceChange5m",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "priceChange1h",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "volume",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "oracleConfidence",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMarketState",
    "inputs": [
      {
        "name": "strategyId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "state",
        "type": "tuple",
        "internalType": "struct IStrategyTypes.MarketState",
        "components": [
          {
            "name": "price",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "volatility",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "priceChange5m",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "priceChange1h",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "volume",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "oracleConfidence",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setVolatility",
    "inputs": [
      {
        "name": "strategyId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "volatilityBps",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const;
