// Generated by scripts/sync-abis.mjs from out/UniswapV4Venue.sol/UniswapV4Venue.json - do not edit.
// Re-run `npm run sync-abis` after any `forge build`.

export const uniswapV4VenueAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "manager",
        "type": "address",
        "internalType": "contract IPoolManager"
      },
      {
        "name": "swapRouter",
        "type": "address",
        "internalType": "contract PoolSwapTest"
      },
      {
        "name": "hook",
        "type": "address",
        "internalType": "contract IHookStrategyAdapter"
      },
      {
        "name": "poolKey_",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "HOOK",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IHookStrategyAdapter"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MANAGER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPoolManager"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "POOL_ID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "PoolId"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SWAP_ROUTER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract PoolSwapTest"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "executableLiquidity",
    "inputs": [
      {
        "name": "tokenIn",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IExecutableLiquidity.ExecutableLiquidity",
        "components": [
          {
            "name": "virtualLiquidity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "walletLiquidity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "allowance",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deliverableLiquidity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "conditionalLiquidity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "coverageBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "execute",
    "inputs": [
      {
        "name": "tokenIn",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minAmountOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "snapshot",
    "inputs": [
      {
        "name": "tokenIn",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct ILiquidityVenue.VenueSnapshot",
        "components": [
          {
            "name": "venue",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "strategyId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "mode",
            "type": "uint8",
            "internalType": "enum IStrategyTypes.StrategyMode"
          },
          {
            "name": "effectiveLiquidity",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "spreadBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "referencePrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "coverageBps",
            "type": "uint16",
            "internalType": "uint16"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "InsufficientOutput",
    "inputs": [
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minAmountOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownPair",
    "inputs": [
      {
        "name": "tokenIn",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokenOut",
        "type": "address",
        "internalType": "address"
      }
    ]
  }
] as const;
