// Copies each Foundry build artifact's `abi` into src/abis/ as a TypeScript module with
// `as const`, so the frontend never hand-copies or drifts from the compiled contracts.
//
// `as const` is load-bearing, not stylistic: it lets viem/wagmi infer return shapes and revert
// argument tuples from the ABI itself. Without it every chain read comes back `unknown` and has to
// be cast by hand - which is how `useVenueSnapshot`'s hand-written type silently fell behind the
// real struct when `coverageBps` was added.
//
// Re-run after any `forge build`.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "..", "out");
const abisDir = join(here, "..", "src", "abis");

const contracts = ["Solver", "AquaVenue", "UniswapV4Venue", "MockERC20", "MockMarketStateProvider"];

/** `Solver` -> `solverAbi`, `MockERC20` -> `mockERC20Abi`. */
function exportName(name) {
  return `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`;
}

mkdirSync(abisDir, { recursive: true });

const index = [];

for (const name of contracts) {
  const artifactPath = join(outDir, `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const symbol = exportName(name);

  const body = `// Generated by scripts/sync-abis.mjs from out/${name}.sol/${name}.json - do not edit.\n`
    + `// Re-run \`npm run sync-abis\` after any \`forge build\`.\n\n`
    + `export const ${symbol} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;

  writeFileSync(join(abisDir, `${name}.ts`), body);
  index.push(`export { ${symbol} } from "./${name}.js";`);
  console.log(`synced ${name}.ts (${artifact.abi.length} entries)`);
}

writeFileSync(
  join(abisDir, "index.ts"),
  `// Generated by scripts/sync-abis.mjs - do not edit.\n\n${index.join("\n")}\n`
);
console.log(`wrote index.ts`);
