// Copies each Foundry build artifact's `abi` into src/abis/ as a TypeScript module with
// `as const`, so the frontend never hand-copies or drifts from the compiled contracts.
//
// `as const` is load-bearing, not stylistic: it lets viem/wagmi infer return shapes and revert
// argument tuples from the ABI itself. Without it every chain read comes back `unknown` and has to
// be cast by hand - which is how `useVenueSnapshot`'s hand-written type silently fell behind the
// real struct when `coverageBps` was added.
//
// Re-run after any `forge build`.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "..", "out");
const abisDir = join(here, "..", "src", "abis");

const contracts = [
  "Solver",
  "AquaVenue",
  "UniswapV4Venue",
  "MockERC20",
  "MockMarketStateProvider",
  // The strategy screen registers and reads strategies directly against these two.
  "ConditionalLiquidityRegistry",
  "ConditionalLiquidityEngine",
  "StrategyValidator",
];

/** `Solver` -> `solverAbi`, `MockERC20` -> `mockERC20Abi`. */
function exportName(name) {
  return `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`;
}

mkdirSync(abisDir, { recursive: true });

const index = [];

for (const name of contracts) {
  const artifactPath = join(outDir, `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const symbol = exportName(name);

  const body = `// Generated by scripts/sync-abis.mjs from out/${name}.sol/${name}.json - do not edit.\n`
    + `// Re-run \`npm run sync-abis\` after any \`forge build\`.\n\n`
    + `export const ${symbol} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;

  writeFileSync(join(abisDir, `${name}.ts`), body);
  index.push(`export { ${symbol} } from "./${name}.js";`);
  console.log(`synced ${name}.ts (${artifact.abi.length} entries)`);
}

/**
 * SwapVM opcode numbers, read out of 1inch's own `OpcodeList.sol` rather than transcribed.
 *
 * The frontend has to build the same SwapVM program `ConditionalLiquidityProgramLib.build` emits
 * in order to register a strategy, and an opcode is a single byte with no runtime error if it is
 * wrong - the order would simply hash to something nobody has liquidity behind. Generating the
 * numbers from the enum that defines them removes that failure mode.
 */
const opcodeSource = readFileSync(
  join(here, "..", "..", "node_modules", "@1inch", "swap-vm", "src", "libs", "OpcodeList.sol"),
  "utf8"
);

function opcodeOf(name) {
  const match = opcodeSource.match(new RegExp(`/\\* ([0-9a-f]{2}) \\*/ ${name},`));
  if (!match) throw new Error(`opcode ${name} not found in OpcodeList.sol`);
  return parseInt(match[1], 16);
}

const opcodes = { xycSwap: opcodeOf("XYCSwap"), extruction: opcodeOf("Extruction") };
writeFileSync(
  join(abisDir, "swapVmOpcodes.ts"),
  `// Generated by scripts/sync-abis.mjs from @1inch/swap-vm/src/libs/OpcodeList.sol - do not edit.\n\n`
    + `export const SWAP_VM_OPCODES = ${JSON.stringify(opcodes, null, 2)} as const;\n`
);
index.push(`export { SWAP_VM_OPCODES } from "./swapVmOpcodes.js";`);
console.log(`synced swapVmOpcodes.ts (${JSON.stringify(opcodes)})`);

writeFileSync(
  join(abisDir, "index.ts"),
  `// Generated by scripts/sync-abis.mjs - do not edit.\n\n${index.join("\n")}\n`
);
console.log(`wrote index.ts`);
